version: 2.1
jobs:
  build_and_test:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Build'
          command: |
            docker-compose build
          no_output_timeout: '60m'

workflows:
  build_and_push_images:
    jobs:
      - build_and_test
