version: 2.1
jobs:
  toolchains:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Pull remote versions'
          command: |
            docker pull aztecprotocol/cmake:3.15.4 || true
            docker pull aztecprotocol/clang:9.0.0 || true
            docker pull aztecprotocol/crosstool-ng:1.24.0 || true
            docker pull aztecprotocol/crosstool-ng-arm64:latest || true
            docker pull aztecprotocol/mingw:latest || true
      - run:
          name: 'Build'
          command: |
            docker-compose build cmake
            docker-compose build clang
            docker-compose build crosstool-ng
            docker-compose build crosstool-ng-arm64
            docker-compose build mingw
      - run:
          name: 'Push'
          command: |
            docker login -u aztecprotocolci -p "${DOCKERHUB_PASSWORD}"
            docker push aztecprotocol/cmake:3.15.4
            docker push aztecprotocol/clang:9.0.0
            docker push aztecprotocol/crosstool-ng:1.24.0
            docker push aztecprotocol/crosstool-ng-arm64:latest
            docker push aztecprotocol/mingw:latest

  x86_64-linux-gcc:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Build'
          command: docker-compose build x86_64-linux-gcc

  x86_64-linux-clang:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Build'
          command: docker-compose build x86_64-linux-clang

  x86_64-win32-mingw:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Build'
          command: docker-compose build x86_64-win32-mingw
          no_output_timeout: '60m'

  arm64-linux-gcc:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Build'
          command: docker-compose build arm64-linux-gcc

workflows:
  build:
    jobs:
      - toolchains
      - x86_64-linux-gcc:
          requires:
            - toolchains
      - x86_64-linux-clang:
          requires:
            - toolchains
      - x86_64-win32-mingw:
          requires:
            - toolchains
      - arm64-linux-gcc:
          requires:
            - toolchains
