setup_env: &setup_env
  run:
    name: 'Setup environment'
    command: cd .circleci && ./setup_env "$CIRCLE_SHA1" "$CIRCLE_BRANCH" "$CIRCLE_TAG" "$CIRCLE_JOB" "$CIRCLE_REPOSITORY_URL"

version: 2.1
parameters:
  rebuild:
    type: boolean
    default: false

jobs:
  wasm-linux-clang:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build'
          working_directory: barretenberg
          command: cond_spot_run_build barretenberg-wasm-linux-clang 64core ./dockerfiles/Dockerfile.wasm-linux-clang

  x86_64-linux-gcc:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build'
          working_directory: barretenberg
          command: cond_spot_run_build barretenberg-x86_64-linux-gcc 64core ./dockerfiles/Dockerfile.x86_64-linux-gcc

  x86_64-linux-clang:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build'
          working_directory: barretenberg
          command: cond_spot_run_build barretenberg-x86_64-linux-clang 64core ./dockerfiles/Dockerfile.x86_64-linux-clang

  x86_64-linux-clang-assert:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build'
          working_directory: barretenberg
          command: cond_spot_run_build barretenberg-x86_64-linux-clang-assert 64core ./dockerfiles/Dockerfile.x86_64-linux-clang-assert

  barretenberg-tests:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: barretenberg
          command: cond_spot_run_tests barretenberg-x86_64-linux-clang-assert bb-tests

  stdlib-primitives-tests:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: barretenberg
          command: cond_spot_run_tests barretenberg-x86_64-linux-clang-assert stdlib_primitives_tests

  stdlib-recursion-tests:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: barretenberg
          command: cond_spot_run_tests barretenberg-x86_64-linux-clang-assert stdlib_recursion_tests

  tx-rollup-tests:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: barretenberg
          command: cond_spot_run_tests barretenberg-x86_64-linux-clang-assert rollup_proofs_tx_rollup_tests

  root-rollup-tests:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: barretenberg
          command: cond_spot_run_tests barretenberg-x86_64-linux-clang-assert rollup_proofs_root_rollup_tests --gtest_filter=-root_rollup_full_tests.*

  root-rollup-full-tests:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: barretenberg
          command: cond_spot_run_tests barretenberg-x86_64-linux-clang-assert rollup_proofs_root_rollup_tests --gtest_filter=root_rollup_full_tests.*

  root-verifier-tests:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: barretenberg
          command: cond_spot_run_tests barretenberg-x86_64-linux-clang-assert rollup_proofs_root_verifier_tests

  barretenberg-js:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - *setup_env
      - run:
          name: 'Build and test'
          working_directory: barretenberg.js
          command: build barretenberg.js

  blockchain-vks:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build'
          working_directory: blockchain-vks
          command: cond_spot_run_build blockchain-vks 32core

  blockchain:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - *setup_env
      - run:
          name: 'Build'
          working_directory: blockchain
          command: build blockchain

  blockchain-tests:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: blockchain
          command: cond_spot_run_tests blockchain

  halloumi:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - *setup_env
      - run:
          name: 'Build and test'
          working_directory: halloumi
          command: build halloumi

  falafel:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - *setup_env
      - run:
          name: 'Build and test'
          working_directory: falafel
          command: build falafel

  wasabi:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - *setup_env
      - run:
          name: 'Build and test'
          working_directory: wasabi
          command: build wasabi

  sdk:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build and test'
          working_directory: sdk
          command: build sdk

  hummus:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build and test'
          working_directory: hummus
          command: build hummus

  block-explorer:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build and test'
          working_directory: block-explorer
          command: build block-explorer

  documentation:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build and test'
          working_directory: documentation
          command: build documentation

  end-to-end:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build'
          working_directory: end-to-end
          command: build end-to-end

  e2e-prover:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: end-to-end
          command: cond_spot_run_tests end-to-end ./src/e2e_deposit.test.ts 1 1 VerificationKey1x1

  e2e-payment:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: end-to-end
          command: cond_spot_run_tests end-to-end ./src/e2e.test.ts

  e2e-account:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: end-to-end
          command: cond_spot_run_tests end-to-end ./src/e2e_account.test.ts

  e2e-defi:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Test'
          working_directory: end-to-end
          command: cond_spot_run_tests end-to-end ./src/e2e_defi.test.ts

  zk-money:
    docker:
      - image: aztecprotocol/build-image
    resource_class: small
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build and test'
          working_directory: zk-money
          command: cond_spot_run_build zk-money 32core

  website:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build and test'
          working_directory: website
          command: build website

  metrics:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'Build coinbase-exporter'
          working_directory: metrics/coinbase-exporter
          command: build coinbase-exporter
      - run:
          name: 'Build sidecar'
          working_directory: metrics/sidecar
          command: build metrics-sidecar
      - run:
          name: 'Build prometheus'
          working_directory: metrics/prometheus
          command: build prometheus
      - run:
          name: 'Build grafana'
          working_directory: metrics/grafana
          command: build grafana

  deploy-master:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'hummus'
          working_directory: hummus
          command: |
            deploy_ecr hummus
            deploy_s3 hummus
      - run:
          name: 'block-explorer'
          working_directory: block-explorer
          command: |
            deploy_ecr block-explorer
            deploy_s3 block-explorer
      - run:
          name: 'documentation'
          working_directory: documentation
          command: |
            deploy_ecr documentation
            deploy_s3 documentation
      - run:
          name: 'website'
          working_directory: website
          command: |
            deploy_ecr website
            deploy_s3 website
      - run:
          name: 'metrics'
          working_directory: metrics
          command: |
            cd coinbase-exporter && deploy coinbase-exporter && cd ..
            cd ecs-exporter && deploy_terraform && cd ..
            cd sidecar && deploy metrics-sidecar && cd ..
            cd prometheus && deploy prometheus && cd ..
            cd grafana && deploy grafana && cd ..

  deploy-dev:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'barretenberg-x86_64-linux-gcc'
          working_directory: barretenberg
          command: deploy_ecr barretenberg-x86_64-linux-gcc
      - run:
          name: 'barretenberg-x86_64-linux-clang'
          working_directory: barretenberg
          command: deploy_ecr barretenberg-x86_64-linux-clang
      - run:
          name: 'barretenberg-wasm-linux-clang'
          working_directory: barretenberg
          command: deploy_ecr barretenberg-wasm-linux-clang
      - run:
          name: 'barretenberg.js'
          working_directory: barretenberg.js
          command: deploy_ecr barretenberg.js
      - run:
          name: 'blockchain'
          working_directory: blockchain
          command: ./scripts/deploy-dev mainnet-fork
      - run:
          name: 'halloumi'
          working_directory: halloumi
          command: deploy halloumi
      - run:
          name: 'falafel'
          working_directory: falafel
          command: deploy falafel
      - run:
          name: 'sdk'
          working_directory: sdk
          command: deploy_ecr sdk
      - run:
          name: 'wasabi'
          working_directory: wasabi
          command: deploy wasabi
      - run:
          name: 'zk-money'
          working_directory: zk-money
          command: |
            deploy_ecr zk-money
            deploy_s3 zk-money

  deploy-prod:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - checkout
      - *setup_env
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: 'barretenberg.js'
          working_directory: barretenberg.js
          command: |
            deploy_ecr barretenberg.js
            deploy_npm barretenberg.js
      - run:
          name: 'blockchain'
          working_directory: blockchain
          command: |
            deploy_ecr blockchain
            deploy_npm blockchain
      - run:
          name: 'sdk'
          working_directory: sdk
          command: |
            deploy_ecr sdk
            deploy_npm sdk
      - run:
          name: 'halloumi'
          working_directory: halloumi
          command: deploy halloumi
      - run:
          name: 'falafel'
          working_directory: falafel
          command: |
            deploy falafel
            deploy_dockerhub falafel
      - run:
          name: 'zk-money'
          working_directory: zk-money
          command: |
            deploy_ecr zk-money
            deploy_s3 zk-money

tag_filter: &tag_filter
  tags:
    only: /v[0-9]+(\.[0-9]+)*/

workflows:
  build:
    jobs:
      - x86_64-linux-gcc:
          filters: *tag_filter
      - x86_64-linux-clang:
          filters: *tag_filter
      - x86_64-linux-clang-assert:
          filters: *tag_filter
      - wasm-linux-clang:
          filters: *tag_filter
      - barretenberg-tests:
          requires:
            - x86_64-linux-clang-assert
          filters: *tag_filter
      - stdlib-primitives-tests:
          requires:
            - x86_64-linux-clang-assert
          filters: *tag_filter
      - stdlib-recursion-tests:
          requires:
            - x86_64-linux-clang-assert
          filters: *tag_filter
      - tx-rollup-tests:
          requires:
            - x86_64-linux-clang-assert
          filters: *tag_filter
      - root-rollup-tests:
          requires:
            - x86_64-linux-clang-assert
          filters: *tag_filter
      - root-rollup-full-tests:
          requires:
            - x86_64-linux-clang-assert
          filters: *tag_filter
      - root-verifier-tests:
          requires:
            - x86_64-linux-clang-assert
          filters: *tag_filter
      - barretenberg-js:
          requires:
            - wasm-linux-clang
            - x86_64-linux-clang
          filters: *tag_filter
      - blockchain-vks:
          requires:
            - x86_64-linux-clang
          filters: *tag_filter
      - blockchain:
          requires:
            - barretenberg-js
            - blockchain-vks
          filters: *tag_filter
      - blockchain-tests:
          requires:
            - blockchain
          filters: *tag_filter
      - halloumi:
          requires:
            - barretenberg-js
          filters: *tag_filter
      - falafel:
          requires:
            - blockchain
            - halloumi
          filters: *tag_filter
      - sdk:
          requires:
            - falafel
          filters: *tag_filter
      - hummus:
          requires:
            - sdk
      - wasabi:
          requires:
            - sdk
      - block-explorer:
          requires:
            - sdk
      - zk-money:
          requires:
            - sdk
          filters: *tag_filter
      - end-to-end:
          requires:
            - sdk
          filters: *tag_filter
      - e2e-prover:
          requires:
            - end-to-end
          filters: *tag_filter
      - e2e-payment:
          requires:
            - end-to-end
          filters: *tag_filter
      - e2e-account:
          requires:
            - end-to-end
          filters: *tag_filter
      - e2e-defi:
          requires:
            - end-to-end
          filters: *tag_filter
      - website
      - metrics
      - deploy-master:
          requires:
            - website
            - block-explorer
            - hummus
            - metrics
          filters:
            branches:
              only:
                - master
      - deploy-dev:
          requires:
            - x86_64-linux-gcc
            - barretenberg-tests
            - stdlib-primitives-tests
            - stdlib-recursion-tests
            - tx-rollup-tests
            - root-rollup-tests
            - root-rollup-full-tests
            - root-verifier-tests
            - blockchain-tests
            - e2e-prover
            - e2e-payment
            - e2e-account
            - e2e-defi
            - wasabi
            - zk-money
          filters:
            branches:
              only:
                - master
                - defi-bridge-project
      - deploy-prod:
          requires:
            - e2e-prover
            - e2e-payment
            - e2e-account
            - e2e-defi
            - zk-money
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
